// Pin assignments used for the Robot

// PIN NAME    Num DIR   TYPE

LEFT_DRIVE_0      2   //OUTPUT  PWM    
LEFT_DRIVE_1      3   //OUTPUT  PWM    
RIGHT_DRIVE_0     4   //OUTPUT  PWM    
RIGHT_DRIVE_1     5   //OUTPUT  PWM    
FORK_LIFT_0       6   //OUTPUT  PWM    
FORK_LIFT_1       7   //OUTPUT  PWM    
ACCL_X            A0  //INPUT   ANALOG     
ACCL_Y            A1  //INPUT   ANALOG     
ACCL_Z            A2  //INPUT   ANALOG     
SWITCH_BANK_1     40  //INPUT   DIGITAL    
SWITCH_BANK_2     41  //INPUT   DIGITAL    
SWITCH_BANK_3     42  //INPUT   DIGITAL    
SWITCH_BANK_4     43  //INPUT   DIGITAL    
BUTTON            44  //INPUT   DIGITAL    
DRIVE_MOT_POWER   45  //INPUT   DIGITAL    
LIFT_MOT_POWER    46  //INPUT   DIGITAL    
RED_LED           47  //OUTPUT  DIGITAL    
YELLOW_LED        48  //OUTPUT  DIGITAL    
GREEN_LED         49  //OUTPUT  DIGITAL    
LIFT_TOP_SENSOR   50  //INPUT   DIGITAL    
LIFT_BOT_SENSOR   51  //INPUT   DIGITAL    
IR_SENSOR_MOTOR   8   //OUTPUT  PWM    
FRONT_ULTRA_TRIG  28  //OUTPUT  DIGITAL    
FRONT_ULTRA_PING  29  //INPUT   DIGITAL    
SIDE_ULTRA_TRIG   26  //OUTPUT  DIGITAL    
SIDE_ULTRA_PING   27  //INPUT   DIGITAL    
RADIO_0           30  //OUTPUT  DIGITAL    
RADIO_1           31  //OUTPUT  DIGITAL    
IR_SENSOR_PING    A3  //INPUT   ANALOG  
